# Generated by Django 5.0.1 on 2024-01-17 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField()),
                ('height', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('goalWeight', models.IntegerField()),
                ('weeklyplan', models.FloatField()),
                ('endgoal_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
