# Generated by Django 5.0.1 on 2024-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodCategory', models.CharField(max_length=100)),
                ('FoodItem', models.CharField(max_length=100)),
                ('per100grams', models.CharField(max_length=100)),
                ('Cals_per100grams', models.CharField(max_length=100)),
                ('KJ_per100grams', models.CharField(max_length=100)),
            ],
        ),
    ]
