# Generated by Django 5.0.1 on 2024-03-08 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailytrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytrack',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='dailytrack',
            name='currdate',
        ),
        migrations.AddField(
            model_name='dailytrack',
            name='calories',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='dailytrack',
            name='current_date',
            field=models.DateField(default=datetime.date(2024, 3, 8)),
        ),
        migrations.AddField(
            model_name='dailytrack',
            name='fat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='dailytrack',
            name='serving_size',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='dailytrack',
            name='type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='carbs',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='cholesterol',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='fiber',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='food',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='potassium',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='protein',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='sodium',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailytrack',
            name='sugar',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
